name = "prisma-mongodb-cloudflare"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-08-02"
webpack_config = "webpack.config.js"

